// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUb7n_uUmdAkB_tGThrIW21EI5E9C9OE',
    appId: '1:124626164522:web:f88698b3dd9d6b94415c53',
    messagingSenderId: '124626164522',
    projectId: 'sekho-7f844',
    authDomain: 'sekho-7f844.firebaseapp.com',
    storageBucket: 'sekho-7f844.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9uezbZJZBQxftOb2BvcN4aaBS12XVNs',
    appId: '1:124626164522:android:cf58a10563d4d4a7415c53',
    messagingSenderId: '124626164522',
    projectId: 'sekho-7f844',
    storageBucket: 'sekho-7f844.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbJeUvqL2psS0cq9LaBlZvVuYdJt1G1M',
    appId: '1:124626164522:ios:b2526f96f942f339415c53',
    messagingSenderId: '124626164522',
    projectId: 'sekho-7f844',
    storageBucket: 'sekho-7f844.appspot.com',
    iosClientId: '124626164522-osvr1fr853mlfdar5ors1d8vl1713bt9.apps.googleusercontent.com',
    iosBundleId: 'com.mediacity.eclasstest',
  );
}
